name: docker-build

on:
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image and push
        run: |
          TAG=${GITHUB_REF##*/}
          docker build -t johz/apisix-plugin-dev:${TAG} .
          docker push johz/apisix-plugin-dev:${TAG}
